# Adapted from: https://github.com/mistralai/mistral-src

FROM runpod/pytorch:2.1.1-py3.10-cuda12.1.1-devel-ubuntu22.04 as base

WORKDIR /workspace

RUN apt update -y && \
    apt install nano htop nvtop ncdu -y

RUN pip uninstall torchaudio torchvision -y && \
    pip install vllm==0.3.3

COPY entrypoint.sh .

RUN chmod +x /workspace/entrypoint.sh

ENTRYPOINT ["/workspace/entrypoint.sh"]